from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

from deno import find_deno_bin

REPO_ROOT = Path(__file__).resolve().parents[1]
WIDGET_ENTRY = REPO_ROOT / "widget" / "index.ts"
ASSET_DIR = REPO_ROOT / "src/jupyter_book_marimo/assets"
DEFAULT_OUTPUT = ASSET_DIR / "container-widget.mjs"
BRIDGE_CSS_OUTPUT = ASSET_DIR / "islands-bridge.css"
BRIDGE_CSS_SOURCE = json.loads((REPO_ROOT / "deno.json").read_text(encoding="utf-8"))[
    "imports"
]["@marimo-team/mdx-marimo/styles.css"]
NPM_CACHE_MODULE_RE = re.compile(
    r"(?P<prefix>(?:// |[\"']))[^\n\"']*npm/registry\.npmjs\.org/"
    r"(?P<package>(?:@[^/]+/)?[^/]+)/(?P<version>[^/]+)/(?P<path>[^\"'\n]+)"
)
BANNER = (
    "// Generated from widget/ and the mdx-marimo bridge.\n"
    "// Do not edit this file directly.\n"
)


def resolve_output(argv: list[str]) -> Path:
    if not argv:
        return DEFAULT_OUTPUT
    output = Path(argv[0])
    return output if output.is_absolute() else REPO_ROOT / output


def bundle(source: str | Path, *options: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            find_deno_bin(),
            "bundle",
            "--quiet",
            *options,
            str(source),
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def normalize_bundle(source: str) -> str:
    def replace(match: re.Match[str]) -> str:
        return (
            f"{match.group('prefix')}npm:{match.group('package')}"
            f"@{match.group('version')}/{match.group('path')}"
        )

    return NPM_CACHE_MODULE_RE.sub(replace, source)


def main(argv: list[str]) -> int:
    javascript = bundle(
        WIDGET_ENTRY,
        "--platform",
        "browser",
        "--format",
        "esm",
    )
    if javascript.returncode != 0:
        sys.stderr.write(javascript.stderr)
        return javascript.returncode

    styles = bundle(BRIDGE_CSS_SOURCE, "--minify")
    if styles.returncode != 0:
        sys.stderr.write(styles.stderr)
        return styles.returncode

    resolve_output(argv).write_text(
        f"{BANNER}{normalize_bundle(javascript.stdout)}",
        encoding="utf-8",
    )
    BRIDGE_CSS_OUTPUT.write_text(styles.stdout, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
