from __future__ import annotations

from pathlib import Path
import subprocess
import sys

from deno import find_deno_bin

REPO_ROOT = Path(__file__).resolve().parents[1]
WIDGET_ENTRY = REPO_ROOT / "widget" / "container-widget.ts"
DEFAULT_OUTPUT = REPO_ROOT / "src/jupyter_book_marimo/assets/container-widget.mjs"
BANNER = "\n".join(
    [
        "// Generated by `make widget-build` from widget/.",
        "// Do not edit this file directly.",
        "",
    ]
)


def resolve_output(argv: list[str]) -> Path:
    if not argv:
        return DEFAULT_OUTPUT
    output = Path(argv[0])
    return output if output.is_absolute() else REPO_ROOT / output


def main(argv: list[str]) -> int:
    output = resolve_output(argv)
    result = subprocess.run(
        [
            find_deno_bin(),
            "bundle",
            "--quiet",
            "--platform",
            "browser",
            "--format",
            "esm",
            str(WIDGET_ENTRY),
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return result.returncode

    output.write_text(f"{BANNER}{result.stdout}", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
